# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: "tailpipe"
    binary: "{{ .ProjectName }}.plugin"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - GOPRIVATE=github.com/turbot
    flags:
      - -tags=netgo
  - id: "tailpipe-linux-arm64"
    binary: "{{ .ProjectName }}.plugin"
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - GOPRIVATE=github.com/turbot
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -tags=netgo

archives:
  - format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
